### ISSUE TITLE
Deprecated TCA entries

### ISSUE THREAD

**Issue by froemken** [jweiland-net/avalex#10]
Hello JW Team,

I'm using Avalex in one of your Projects. While Upgrading your Project, the TCA migration check criticized following lines:

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_avalex_configuration['ctrl']['versioningWS']
The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_avalex_configuration['ctrl']['versioning_followPages']
The TCA setting 'versioningWS' was set to a boolean value in TCA tx_avalex_legaltext['ctrl']['versioningWS']
The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_avalex_legaltext['ctrl']['versioning_followPages']

Nice greetings from your College

Stefan

**Comment by pascal20997** [comment]
Hello Stefan,

you're right I'll add some conditions to keep the TCA compatible with TYPO3 6.2 - 10.4.

Thanks :)
