### ISSUE TITLE
Spam prevention

### ISSUE THREAD

**Issue by Cretection** [jweiland-net/avalex#13]
Many thanks for the extension. So far everything works fine. However, I have a suggestion for improvement. The offer adds email addresses in plain text in a few places. Unfortunately this is one of the main reasons for spam nowadays. 

It would be nice if the extension takes into account the chosen settings in the config. So the email is created with typolink.

**Comment by pascal20997** [comment]
Hey @Cretection, this is a good idea. I try to implement the feature as soon as possible.

**Comment by Cretection** [comment]
Top - Thank You!
