### ISSUE TITLE
TYPO3 v11 support

### ISSUE THREAD

**Issue by bmack** [jweiland-net/avalex#14]
Hey jweiland team,

first: thank you for this great extension!

One question that popped up recently: Are there any plans to support TYPO3 v11?

Thanks.
Benni.

**Comment by pascal20997** [comment]
Hey Benni,

yes I'll upload the latest avalex version in couple minutes. It's compatible with v11 but has no new features yet. I'll release the latest version (composer, TER) when the spam feature from #13 is implemented. Feel free to use the master in your TYPO3 v11 😄 .

Greetings,
Pascal

**Comment by bmack** [comment]
Awesome. Thanks.
