### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by griesi007** [jweiland-net/avalex#18]
Currently ext_localconf.php in 6.4.0 ist not PHP 8.0 compatible. Following PHP Warnings are raised:

Core: Error handler (BE): PHP Warning: Undefined array key "avalex_content" in typo3conf/ext/avalex/ext_localconf.php line 76

Core: Error handler (BE): PHP Warning: Undefined array key "avalex" in typo3conf/ext/avalex/ext_localconf.php line 82

Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in typo3conf/ext/avalex/ext_localconf.php line 82

**Comment by pascal20997** [comment]
Hello @griesi007,

thanks for your report, I'll fix this today and release a new version soon.
