### ISSUE TITLE
{{env::request}} wird nicht aufgelöst

### ISSUE THREAD

**Issue by Mikel2411** [jweiland-net/avalex#20]
Wir verwenden Avalex 6.5.0 in zahlreichen Websites ohne Probleme. Jedoch haben wir in einer Website das Problem, dass die URL der Anker-Links nicht richtig aufgelöst wird. Z.B. Im Quellcode <a href="{{env::request}}#verantwortliche-stelle">II. Verantwortliche Stelle</a>. Im Frontend: https://www.naegele-ortho.de/%7B%7Benv::request%7D%7D#verantwortliche-stelle
Was könnte die Ursache sein

**Comment by froemken** [comment]
Hallo @Mikel2411 

ich habe Probleme das nachzuvollziehen. Diese 2 geschweiften Klammern sind typische Platzhalter für Symfony. Dies setzen wir überhaupt nicht ein. Ich habe den kompletten Extensionordner nach `ENV`, `ENV:` und `{{` durchsucht. Außer in der Deploymentkonfiguration habe ich nichts dazu gefunden.

Ich habe den Technischen Ansprechpartner mal über dieses Ticket informiert. Evtl. hat er eine Spur einer Idee, was das sein könnte.

Schönen Start ins Wochenende

Stefan

**Comment by froemken** [comment]
Ich kann das Problem auch weiterhin nicht lokalisieren. Wir arbeiten nicht mit diesen Platzhaltern.
Ich schließe das Ticket jetzt. Falls noch weitere Infos kommen, gerne das Ticket wieder öffnen.

Stefan
