### ISSUE TITLE
Compatibility with TYPO3 v9 LTS

### ISSUE THREAD

**Issue by bmack** [jweiland-net/avalex#7]
Hey,

are there any concrete plans to release a TYPO3 v9 LTS compatible version?

**Comment by bmack** [comment]
This would also mean that composer requires "typo3/cms-core" instead of "typo3/cms"

**Comment by pascal20997** [comment]
Yes TYPO3 v9 LTS support will come very very soon

**Comment by pascal20997** [comment]
Just released the new version for TYPO3 v9 LTS :)
